/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionContratsTravail;

import classesMetier.ContratCession;
import classesMetier.ContratTravail;
import classesMetier.Intermittent;
import classesMetier.Representation;
import classesMetier.User;
import javax.swing.JOptionPane;
import nezdames.serialisation.NezDamesSerialisation;

/**
 *
 * @author paco
 */
public class ContratTravailAjouter extends javax.swing.JFrame {

    /**
     * Creates new form ContratTravailAjouter
     */
    public ContratTravailAjouter() {
        initComponents();
        for (ContratCession unContrat : NezDamesSerialisation.lesContratsCession ){
            CessionBox.addItem(unContrat.getNumeroContratCession());
            
        }
        for (Intermittent unIntermittent : NezDamesSerialisation.lesIntermittents ){
            Intermittentbox.addItem(unIntermittent.getNomIntermittent());
            
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        lblImageManu = new javax.swing.JLabel();
        lblTitre3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtrole = new javax.swing.JTextField();
        txtdatedebut = new javax.swing.JTextField();
        txtnbheure = new javax.swing.JTextField();
        txtdaterepresen = new javax.swing.JTextField();
        txtlieu = new javax.swing.JTextField();
        txtdatecrea = new javax.swing.JTextField();
        txtheure = new javax.swing.JTextField();
        BtnEnvoyer = new javax.swing.JButton();
        BtnAnnuler = new javax.swing.JButton();
        lblImageOlivier = new javax.swing.JLabel();
        Intermittentbox = new javax.swing.JComboBox();
        CessionBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 51, 0));

        lblImageManu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portraitManu.png"))); // NOI18N

        lblTitre3.setFont(new java.awt.Font("Hannotate SC", 1, 18)); // NOI18N
        lblTitre3.setForeground(new java.awt.Color(255, 153, 51));
        lblTitre3.setText("CRÉATION D'UN CONTRAT DE TRAVAIL");

        jLabel1.setText("Role");

        jLabel2.setText("Date début");

        jLabel3.setText("Heure");

        jLabel4.setText("Nombre d'heure");

        jLabel5.setText("Date représentation");

        jLabel6.setText("Lieu représentaion");

        jLabel7.setText("Date création");

        jLabel8.setText("Contrat cession");

        jLabel9.setText("Intermittent");

        txtrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtroleActionPerformed(evt);
            }
        });

        txtdatedebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatedebutActionPerformed(evt);
            }
        });

        txtnbheure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnbheureActionPerformed(evt);
            }
        });

        txtdaterepresen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaterepresenActionPerformed(evt);
            }
        });

        txtlieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlieuActionPerformed(evt);
            }
        });

        txtdatecrea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatecreaActionPerformed(evt);
            }
        });

        txtheure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtheureActionPerformed(evt);
            }
        });

        BtnEnvoyer.setText("Envoyer");
        BtnEnvoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnvoyerActionPerformed(evt);
            }
        });

        BtnAnnuler.setText("Annuler");
        BtnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnnulerActionPerformed(evt);
            }
        });

        lblImageOlivier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/portraitOlivier.png"))); // NOI18N

        Intermittentbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntermittentboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnEnvoyer)
                .addGap(130, 130, 130)
                .addComponent(BtnAnnuler)
                .addGap(280, 280, 280))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnbheure)
                            .addComponent(txtdatedebut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(txtrole, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdaterepresen))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(41, 41, 41)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(26, 26, 26)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(52, 52, 52)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdatecrea)
                            .addComponent(txtlieu)
                            .addComponent(Intermittentbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CessionBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtheure, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblImageManu)
                .addGap(160, 160, 160)
                .addComponent(lblTitre3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(lblImageOlivier)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImageManu)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblTitre3))
                    .addComponent(lblImageOlivier, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtdatedebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtheure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnbheure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtdaterepresen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdatecrea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CessionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Intermittentbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEnvoyer)
                    .addComponent(BtnAnnuler)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdatedebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatedebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatedebutActionPerformed

    private void txtroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtroleActionPerformed

    private void txtdatecreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatecreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatecreaActionPerformed

    private void BtnEnvoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnvoyerActionPerformed
        if (txtrole.getText().compareTo("") == 0) {
            JOptionPane.showMessageDialog(null, "Il faut saisir le role");
        } else {
            if (txtdatedebut.getText().compareTo("") == 0) {
                JOptionPane.showMessageDialog(null, "Il faut saisir la date de debut");
            } else {
                if (txtdatecrea.getText().compareTo("") == 0) {
                    JOptionPane.showMessageDialog(null, "Il faut saisir la date de création");
                } else {
                    if (txtheure.getText().compareTo("") == 0) {
                        JOptionPane.showMessageDialog(null, "Il faut saisir l'heure");
                    } else {
                        if (txtnbheure.getText().compareTo("") == 0) {
                            JOptionPane.showMessageDialog(null, "Il faut ne nombre d'heure");
                        } else {
                            if (txtdaterepresen.getText().compareTo("") == 0) {
                                JOptionPane.showMessageDialog(null, "Il faut saisir la date de representation");
                            } else {
                                if (txtlieu.getText().compareTo("") == 0) {
                                    JOptionPane.showMessageDialog(null, "Il faut saisir le lieux");
                                } 
                                                        // ajout d'un user à la collection lesUsers
                                                        
                                                        // ajout d'un intermittent à la collection lesIntermittents
                                Intermittent unintermittent = null;
                                                        for (Intermittent a1 : NezDamesSerialisation.lesIntermittents){
                                                            if (a1.getNomIntermittent()==Intermittentbox.getSelectedItem()){
                                                        
                                                        unintermittent = a1;
                            }
                            }
                            ContratCession nouveauContrat = null;
                            for (ContratCession a2 : NezDamesSerialisation.lesContratsCession){
                            if (a2.getNumeroContratCession()==CessionBox.getSelectedItem()){    
                            
                                nouveauContrat = a2;
                            }
                            }
                                                        NezDamesSerialisation.lesContratsTravail.add(new ContratTravail(txtrole.getText(),
                                                                txtdatedebut.getText(), 
                                                                txtdatecrea.getText(),
                                                                txtheure.getText(), 
                                                                Integer.parseInt(txtnbheure.getText()), 
                                                                txtdaterepresen.getText(), txtlieu.getText(),nouveauContrat,unintermittent,false
                                                        
                                                        ));
                                                                 
                                                        
                                                        JOptionPane.showMessageDialog(null, "");

                                                        this.dispose();
                                                    
                                                
                                            
                                        
                                    
                                
                            
                        
                    
                
            
        
                                             
        
                            }}}}}}                                               
    }//GEN-LAST:event_BtnEnvoyerActionPerformed

    private void txtheureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtheureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtheureActionPerformed

    private void txtnbheureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnbheureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnbheureActionPerformed

    private void txtdaterepresenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaterepresenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaterepresenActionPerformed

    private void txtlieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlieuActionPerformed

    private void BtnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnnulerActionPerformed
        this.dispose();


    }//GEN-LAST:event_BtnAnnulerActionPerformed

    private void IntermittentboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntermittentboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntermittentboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContratTravailAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContratTravailAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContratTravailAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContratTravailAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContratTravailAjouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnnuler;
    private javax.swing.JButton BtnEnvoyer;
    private javax.swing.JComboBox CessionBox;
    private javax.swing.JComboBox Intermittentbox;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImageManu;
    private javax.swing.JLabel lblImageOlivier;
    private javax.swing.JLabel lblTitre3;
    private javax.swing.JTextField txtdatecrea;
    private javax.swing.JTextField txtdatedebut;
    private javax.swing.JTextField txtdaterepresen;
    private javax.swing.JTextField txtheure;
    private javax.swing.JTextField txtlieu;
    private javax.swing.JTextField txtnbheure;
    private javax.swing.JTextField txtrole;
    // End of variables declaration//GEN-END:variables
}
